name: Python Classroom Autograding

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-python-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Verificação de Arquivos Python
        id: verificacao_python
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Verificação de Arquivos Python
          command: python3 -m py_compile *.py
          timeout: 10
          max-score: 1

      - name: Exercício 01 - Verificação de Idade para Ingresso
        id: exercicio_01_py
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Exercício 01 - Verificação de Idade para Ingresso
          command: python3 .grading/grade.py ex1
          timeout: 20
          max-score: 1

      - name: Exercício 02 - Cálculo de Média
        id: exercicio_02_py
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Exercício 02 - Cálculo de Média
          command: python3 .grading/grade.py ex2
          timeout: 20
          max-score: 1

      - name: Exercício 03 - Sistema de Descontos
        id: exercicio_03_py
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Exercício 03 - Sistema de Descontos
          command: python3 .grading/grade.py ex3
          timeout: 20
          max-score: 1

      - name: Exercício 04 - Cálculo de INSS
        id: exercicio_04_py
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Exercício 04 - Cálculo de INSS
          command: python3 .grading/grade.py ex4
          timeout: 20
          max-score: 2

      - name: Exercício 05 - Cálculo de Imposto de Renda
        id: exercicio_05_py
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Exercício 05 - Cálculo de Imposto de Renda
          command: python3 .grading/grade.py ex5
          timeout: 20
          max-score: 2

      - name: Exercício 06 - Cálculo de Salário Líquido
        id: exercicio_06_py
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Exercício 06 - Cálculo de Salário Líquido
          command: python3 .grading/grade.py ex6
          timeout: 20
          max-score: 2

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          VERIFICACAO_PYTHON_RESULTS: "${{steps.verificacao_python.outputs.result}}"
          EXERCICIO_01_PY_RESULTS: "${{steps.exercicio_01_py.outputs.result}}"
          EXERCICIO_02_PY_RESULTS: "${{steps.exercicio_02_py.outputs.result}}"
          EXERCICIO_03_PY_RESULTS: "${{steps.exercicio_03_py.outputs.result}}"
          EXERCICIO_04_PY_RESULTS: "${{steps.exercicio_04_py.outputs.result}}"
          EXERCICIO_05_PY_RESULTS: "${{steps.exercicio_05_py.outputs.result}}"
          EXERCICIO_06_PY_RESULTS: "${{steps.exercicio_06_py.outputs.result}}"
        with:
          runners: verificacao_python,exercicio_01_py,exercicio_02_py,exercicio_03_py,exercicio_04_py,exercicio_05_py,exercicio_06_py